import { readFileSync, readdirSync } from 'node:fs';
import { defineConfig } from 'vitest/config';
import type { Plugin } from 'vite';
import { guidePage } from './src/features/help/guidePage';
import { buildLocales, buildManifest } from './src/manifest';

/** Senuma icons, generated by scripts/brand-icons.mjs. (assets/icons holds the 1.x icons and is left alone.) */
const ICON_DIR = 'src/assets/brand';
/** Brand marks for starter apps; generated by scripts/brand-marks.mjs. */
const MARK_DIR = 'src/assets/marks';
/** Packaged photographs and their gallery previews; produced by scripts/wallpapers-encode.mjs. */
const WALLPAPER_DIR = 'src/assets/wallpapers';
/** Set by `npm run build:e2e`; see src/manifest.ts. */
const E2E_BUILD = process.env.BOS_E2E === '1';

/** The help page's own words, per guide language (the guide text itself is docs/guide/<lang>.md). */
const GUIDE_CHROME = {
    en: { lang: 'en', title: 'Senuma User Guide', other: { href: 'tr.html', label: 'Türkçe', lang: 'tr' }, top: 'Back to top' },
    tr: { lang: 'tr', title: 'Senuma Kullanım Kılavuzu', other: { href: 'en.html', label: 'English', lang: 'en' }, top: 'Başa dön' },
};

/** Emits the extension manifest (generated from brand constants), icons, service worker and the user guide. */
function extensionFiles(): Plugin {
    return {
        name: 'extension-files',
        apply: 'build',
        generateBundle() {
            this.emitFile({
                type: 'asset',
                fileName: 'manifest.json',
                source: JSON.stringify(buildManifest({ grantOptional: E2E_BUILD }), null, 2),
            });
            for (const [fileName, source] of Object.entries(buildLocales())) this.emitFile({ type: 'asset', fileName, source });
            for (const file of readdirSync(ICON_DIR)) {
                if (!file.endsWith('.png')) continue;
                this.emitFile({ type: 'asset', fileName: `icons/${file}`, source: readFileSync(`${ICON_DIR}/${file}`) });
            }
            for (const file of readdirSync(MARK_DIR)) {
                if (file.endsWith('.svg')) this.emitFile({ type: 'asset', fileName: `marks/${file}`, source: readFileSync(`${MARK_DIR}/${file}`) });
            }
            for (const file of readdirSync(WALLPAPER_DIR)) {
                if (file.endsWith('.webp')) this.emitFile({ type: 'asset', fileName: `wallpapers/${file}`, source: readFileSync(`${WALLPAPER_DIR}/${file}`) });
            }
            this.emitFile({ type: 'asset', fileName: 'background.js', source: readFileSync('src/background.js') });
            // The user guide, packaged: it opens offline and asks nothing of any server.
            for (const [lang, chrome] of Object.entries(GUIDE_CHROME)) {
                this.emitFile({ type: 'asset', fileName: `help/${lang}.html`, source: guidePage(readFileSync(`docs/guide/${lang}.md`, 'utf8'), chrome) });
            }
        },
    };
}

export default defineConfig({
    base: '',
    plugins: [extensionFiles()],
    build: {
        outDir: E2E_BUILD ? 'dist-e2e' : 'dist',
        target: 'chrome120',
        modulePreload: { polyfill: false },
        rollupOptions: {
            input: { newtab: 'newtab.html' },
            output: {
                // Chunks made only of the help feature are named help-*, so their size is budgeted on its own line.
                chunkFileNames: chunk => (chunk.moduleIds.length && chunk.moduleIds.every(id => id.includes('/src/features/help/'))
                    ? `assets/help-${chunk.moduleIds.some(id => id.includes('/strings-tr')) ? 'tr-' : ''}[hash].js`
                    : 'assets/[name]-[hash].js'),
            },
        },
    },
    test: { environment: 'node', include: ['src/**/*.test.ts', 'site/**/*.test.ts'] },
});
