import { readFileSync, readdirSync } from 'node:fs';
import { loadEnv } from 'vite';
import { defineConfig } from 'vitest/config';
import type { Plugin } from 'vite';
import { buildManifest } from './src/manifest';

/** Senuma icons, generated by scripts/brand-icons.mjs. (assets/icons holds the 1.x icons and is left alone.) */
const ICON_DIR = 'src/assets/brand';
/** Brand marks for starter apps; generated by scripts/brand-marks.mjs. */
const MARK_DIR = 'src/assets/marks';
/** Packaged photographs and their gallery previews; produced by scripts/wallpapers-encode.mjs. */
const WALLPAPER_DIR = 'src/assets/wallpapers';
/** Set by `npm run build:e2e`; see src/manifest.ts. */
const E2E_BUILD = process.env.BOS_E2E === '1';


/** Emits the extension manifest (generated from brand constants), icons and service worker. */
function extensionFiles(sync: string | undefined, key: string | undefined): Plugin {
    return {
        name: 'extension-files',
        apply: 'build',
        generateBundle() {
            this.emitFile({
                type: 'asset',
                fileName: 'manifest.json',
                source: JSON.stringify(buildManifest({ grantOptional: E2E_BUILD, signIn: sync === 'firebase', key }), null, 2),
            });
            for (const file of readdirSync(ICON_DIR)) {
                if (!file.endsWith('.png')) continue;
                this.emitFile({ type: 'asset', fileName: `icons/${file}`, source: readFileSync(`${ICON_DIR}/${file}`) });
            }
            for (const file of readdirSync(MARK_DIR)) {
                if (file.endsWith('.svg')) this.emitFile({ type: 'asset', fileName: `marks/${file}`, source: readFileSync(`${MARK_DIR}/${file}`) });
            }
            for (const file of readdirSync(WALLPAPER_DIR)) {
                if (file.endsWith('.webp')) this.emitFile({ type: 'asset', fileName: `wallpapers/${file}`, source: readFileSync(`${WALLPAPER_DIR}/${file}`) });
            }
            this.emitFile({ type: 'asset', fileName: 'background.js', source: readFileSync('src/background.js') });
        },
    };
}

export default defineConfig(({ mode }) => {
    /** `npm run build:sync` (emulator) or `build:sync:firebase` (a real project): builds with sync. Never packaged. */
    const env = { ...process.env, ...loadEnv(mode, process.cwd(), ['VITE_', 'SENUMA_']) };
    const SYNC_BUILD = env.VITE_SENUMA_SYNC === 'emulator' || env.VITE_SENUMA_SYNC === 'firebase';
    return {
    base: '',
    plugins: [extensionFiles(SYNC_BUILD ? env.VITE_SENUMA_SYNC : undefined, SYNC_BUILD ? env.SENUMA_EXTENSION_KEY : undefined)],
    build: {
        outDir: E2E_BUILD ? 'dist-e2e' : SYNC_BUILD ? 'dist-sync' : 'dist',
        target: 'chrome120',
        modulePreload: { polyfill: false },
        rollupOptions: { input: { newtab: 'newtab.html' } },
    },
    test: { environment: 'node', include: ['src/**/*.test.ts'] },
    };
});
