/**
 * Words for Account & Sync. Kept out of the main dictionaries so that nobody who does not open
 * this screen loads them.
 *
 * Every sentence here has to stay true of what the code does. In particular: the workspace is
 * encrypted on the device before it is sent; that is all that is claimed. Nothing here says
 * that plaintext can never be reached under any circumstances, and nothing says a removed
 * device is locked out.
 */
import { currentLanguage } from '../../i18n';

const en = {
    title: 'Account & Sync',
    testBuild: 'Test build: sign-in here is a local stand-in, not Google, and the data goes to an emulator on this computer.',
    devBuild: 'Development build: sync goes to Senuma’s development project. Use test data only.',

    'out.lede': 'Senuma works without an account. Everything is stored on this device.',
    'out.what': 'Sync keeps your Spaces, links, Modes, dock, search shortcuts and appearance the same on your devices.',
    'out.signin': 'Signing in with Google is used only to know which encrypted copy is yours. Senuma receives your e-mail address and nothing else from your Google account.',
    'out.encrypted': 'Your workspace is encrypted before it leaves this device, with a key made on this device. The service that stores it cannot read it.',
    'out.local': 'Pages you opened, recently closed pages, what you search for and pictures you added as wallpapers are not uploaded.',
    'out.visible': 'What is not hidden: your e-mail address, when your devices sync, and how large the encrypted copy is.',
    'out.analytics': 'Senuma has no analytics.',
    'out.action': 'Continue with Google',
    'out.removed': 'This device was removed from sync on another device. Everything on this device is still here.',
    connecting: 'Connecting…',

    'new.title': 'Save your recovery key',
    'new.body': 'This key is what unlocks your synced workspace on another device. It is made on this device and is not sent anywhere.',
    'new.warning': 'Without it, nobody can restore the cloud copy, including us. Your data on this device does not depend on it.',
    'new.copy': 'Copy',
    'new.copied': 'Copied',
    'new.download': 'Save as a file',
    'new.confirmLabel': 'To confirm you saved it, type its last four characters',
    'new.confirm': 'Turn on sync',
    'new.cancel': 'Cancel',
    'new.nothingYet': 'Nothing has been uploaded yet.',

    'key.title': 'Enter your recovery key',
    'key.body': 'A synced workspace already exists for this account. Enter the recovery key you saved when you turned sync on. It is checked on this device.',
    'key.changed': 'The recovery key was changed on another device. Enter the new one.',
    'key.placeholder': 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
    'key.action': 'Unlock',
    'key.invalid': 'That is not the recovery key for this account. Nothing was changed.',
    'key.lost': 'I lost my recovery key',
    'lost.title': 'Without the recovery key',
    'lost.body': 'The cloud copy cannot be read by anyone without the key, so it cannot be recovered. A device that is already syncing can show the key: Account & Sync → Recovery key.',
    'lost.option': 'If no device has it, you can delete the cloud copy and start sync again from what is on this device. Nothing on this device is removed.',
    'lost.action': 'Delete the cloud copy and start again',
    'lost.back': 'Back',

    'first.title': 'Two setups',
    'first.body': 'The cloud copy holds {cs} Spaces and {cl} links. This device holds {ds} Spaces and {dl} links. They have never been synced with each other, so nothing is combined until you choose. A restore point of this device is saved first.',
    'first.merge': 'Merge',
    'first.mergeHint': 'Keep everything from both. Links with the same address are not doubled.',
    'first.cloud': 'Use the cloud copy',
    'first.cloudHint': 'Replace this device’s setup with the cloud copy.',
    'first.device': 'Use this device',
    'first.deviceHint': 'Replace the cloud copy with this device’s setup. Other devices will receive it.',

    'state.synced': 'Up to date',
    'state.syncing': 'Syncing…',
    'state.paused': 'Sync is paused on this device',
    'state.offline': 'Offline. Changes are saved on this device and will sync when you are back online.',
    'state.conflict': 'Waiting for your choice',
    'state.error': 'Sync stopped',
    last: 'Last synced {when}',
    never: 'Not synced yet',
    account: 'Signed in as {email}',
    nearLimit: 'Your workspace is close to the size that can be synced. Removing links or picture icons makes room.',

    'do.sync': 'Sync now',
    'do.pause': 'Pause',
    'do.resume': 'Resume',
    'do.signOut': 'Sign out',
    'do.signOutHint': 'Stops sync on this device. Everything on this device stays; the cloud copy stays.',
    'do.retry': 'Try again',
    'do.signInAgain': 'Sign in again',

    'err.auth-expired': 'Your sign-in is no longer valid. Sign in again to carry on. Nothing on this device was changed.',
    'err.missing': 'The cloud copy is gone: cloud data was deleted on another device. Nothing on this device was changed, and nothing was uploaded.',
    'err.missingAction': 'Upload this device’s setup again',
    'err.unreadable': 'The cloud copy could not be read, so it was not applied. Nothing on this device was changed.',
    'err.went-backwards': 'The cloud copy is older than one this device already has. It was not applied.',
    'err.too-large': 'Your workspace is too large to sync. Nothing was sent, and nothing was cut. Everything is still on this device.',
    'err.schema-newer': 'The cloud copy was written by a newer Senuma. Update Senuma on this device to sync.',
    'err.format-newer': 'The cloud copy was written by a newer Senuma. Update Senuma on this device to sync.',
    'err.quota': 'The sync service has reached its limit for today. Sync will try again later; Senuma keeps working.',
    'err.denied': 'The sync service refused the request. Sync will try again.',
    'err.failed': 'Sync could not finish. It will try again.',
    'err.offline': 'The sync service could not be reached.',

    'conflict.title': 'Changed both here and on another device: {n}',
    'conflict.body': 'Nothing has been changed on this device or in the cloud. Choose what to keep. A restore point is saved before anything is applied.',
    'conflict.local': 'This device',
    'conflict.cloud': 'Cloud',
    'conflict.deleted': 'deleted',
    'conflict.order': 'a different order',
    'conflict.none': 'none',
    'conflict.keepLocal': 'Keep this device for all',
    'conflict.keepCloud': 'Keep the cloud for all',
    'conflict.keepBoth': 'Keep both',
    'conflict.keepBothHint': 'This device’s version stays, and the cloud’s version is added beside it as a second link.',
    'conflict.keepBothNo': 'Keeping both is offered only when every difference is in a link.',
    'conflict.apply': 'Apply my choices',
    'conflict.of.item': 'Link “{name}”',
    'conflict.of.space': 'Space “{name}”',
    'conflict.of.group': 'Group “{name}”',
    'conflict.of.mode': 'Mode “{name}”',
    'conflict.of.provider': 'Search provider',
    'conflict.of.pref': 'Setting',
    'conflict.of.dock': 'Dock',
    'conflict.field.exists': 'kept or deleted',
    'conflict.field.order': 'order',
    'conflict.field.group': 'place',

    'devices.title': 'Devices',
    'devices.this': 'this device',
    'devices.last': 'last synced {when}',
    'devices.unreadable': 'A device using an older key',
    'devices.remove': 'Remove',
    'devices.removeHint': 'Removing a device takes it off this list and it stops syncing the next time it tries. It does not erase what that device already has, and it does not sign that device out of your Google account. For a lost device, also change the recovery key.',
    'devices.rename': 'Name of this device',

    'recovery.title': 'Recovery key',
    'recovery.hint': 'Needed to add another device.',
    'recovery.show': 'Show',
    'recovery.confirm': 'Anyone who sees this key and can sign in to your Google account can read your synced workspace. Show it?',
    'recovery.yes': 'Show the key',
    'recovery.hide': 'Hide',
    'recovery.new': 'New recovery key',
    'recovery.newHint': 'Makes a new key and re-encrypts the cloud copy. Other devices stop syncing until the new key is entered on them. It does not take back what a device already has.',
    'recovery.newConfirm': 'Make a new key',

    'delete.title': 'Delete cloud data',
    'delete.hint': 'Removes the encrypted copy, its history, the device list and the keys from the service, and turns sync off here. Everything on this device stays.',
    'delete.confirm': 'Delete cloud data',
    cancel: 'Cancel',

    'bg.missing': 'The background chosen on another device is a picture that is not on this device. This device is showing the theme’s backdrop instead. Nothing was changed on your other devices.',
    'bg.own': 'This device is using its own background. Your other devices keep theirs.',
} as const;

export type SyncKey = keyof typeof en;

const tr: Partial<Record<SyncKey, string>> = {
    title: 'Hesap ve Eşitleme',
    testBuild: 'Deneme sürümü: buradaki oturum açma Google değil, yerel bir taklittir; veriler bu bilgisayardaki bir emülatöre gider.',
    devBuild: 'Geliştirme sürümü: eşitleme Senuma’nın geliştirme projesine gider. Yalnızca deneme verisi kullan.',
    'out.lede': 'Senuma hesap olmadan çalışır. Her şey bu cihazda saklanır.',
    'out.what': 'Eşitleme; Alanlarını, bağlantılarını, Modlarını, dock’unu, arama kısayollarını ve görünümünü cihazlarında aynı tutar.',
    'out.signin': 'Google ile oturum açma yalnızca hangi şifreli kopyanın sana ait olduğunu bilmek için kullanılır. Senuma, Google hesabından yalnızca e-posta adresini alır.',
    'out.encrypted': 'Çalışma alanın bu cihazdan çıkmadan önce, bu cihazda üretilen bir anahtarla şifrelenir. Onu saklayan hizmet okuyamaz.',
    'out.local': 'Açtığın sayfalar, son kapatılan sayfalar, aradıkların ve duvar kâğıdı olarak eklediğin resimler yüklenmez.',
    'out.visible': 'Gizlenmeyenler: e-posta adresin, cihazlarının ne zaman eşitlendiği ve şifreli kopyanın boyutu.',
    'out.analytics': 'Senuma’da analitik yoktur.',
    'out.action': 'Google ile devam et',
    'out.removed': 'Bu cihaz başka bir cihazdan eşitlemeden çıkarıldı. Bu cihazdaki her şey yerinde duruyor.',
    connecting: 'Bağlanıyor…',
    'new.title': 'Kurtarma anahtarını kaydet',
    'new.body': 'Bu anahtar, eşitlenen çalışma alanını başka bir cihazda açar. Bu cihazda üretilir ve hiçbir yere gönderilmez.',
    'new.warning': 'O olmadan bulut kopyasını kimse geri getiremez; biz de. Bu cihazdaki verilerin ona bağlı değildir.',
    'new.copy': 'Kopyala',
    'new.copied': 'Kopyalandı',
    'new.download': 'Dosya olarak kaydet',
    'new.confirmLabel': 'Kaydettiğini doğrulamak için son dört karakterini yaz',
    'new.confirm': 'Eşitlemeyi aç',
    'new.cancel': 'Vazgeç',
    'new.nothingYet': 'Henüz hiçbir şey yüklenmedi.',
    'key.title': 'Kurtarma anahtarını gir',
    'key.body': 'Bu hesap için eşitlenmiş bir çalışma alanı zaten var. Eşitlemeyi açarken kaydettiğin kurtarma anahtarını gir. Anahtar bu cihazda denetlenir.',
    'key.changed': 'Kurtarma anahtarı başka bir cihazda değiştirildi. Yenisini gir.',
    'key.action': 'Aç',
    'key.invalid': 'Bu, bu hesabın kurtarma anahtarı değil. Hiçbir şey değiştirilmedi.',
    'key.lost': 'Kurtarma anahtarımı kaybettim',
    'lost.title': 'Kurtarma anahtarı olmadan',
    'lost.body': 'Bulut kopyasını anahtar olmadan kimse okuyamaz; bu yüzden kurtarılamaz. Hâlâ eşitlenen bir cihaz anahtarı gösterebilir: Hesap ve Eşitleme → Kurtarma anahtarı.',
    'lost.option': 'Hiçbir cihazda yoksa bulut kopyasını silip eşitlemeyi bu cihazdakilerle yeniden başlatabilirsin. Bu cihazdan hiçbir şey silinmez.',
    'lost.action': 'Bulut kopyasını sil ve yeniden başla',
    'lost.back': 'Geri',
    'first.title': 'İki kurulum',
    'first.body': 'Bulut kopyasında {cs} Alan ve {cl} bağlantı var. Bu cihazda {ds} Alan ve {dl} bağlantı var. Birbirleriyle hiç eşitlenmediler; sen seçene kadar hiçbir şey birleştirilmez. Önce bu cihazın bir geri yükleme noktası kaydedilir.',
    'first.merge': 'Birleştir',
    'first.mergeHint': 'İkisindeki her şeyi tut. Aynı adresli bağlantılar çiftlenmez.',
    'first.cloud': 'Bulut kopyasını kullan',
    'first.cloudHint': 'Bu cihazın kurulumunu bulut kopyasıyla değiştir.',
    'first.device': 'Bu cihazı kullan',
    'first.deviceHint': 'Bulut kopyasını bu cihazın kurulumuyla değiştir. Diğer cihazlar bunu alır.',
    'state.synced': 'Güncel',
    'state.syncing': 'Eşitleniyor…',
    'state.paused': 'Eşitleme bu cihazda duraklatıldı',
    'state.offline': 'Çevrimdışı. Değişiklikler bu cihazda saklanıyor; bağlantı gelince eşitlenecek.',
    'state.conflict': 'Seçimin bekleniyor',
    'state.error': 'Eşitleme durdu',
    last: 'Son eşitleme: {when}',
    never: 'Henüz eşitlenmedi',
    account: '{email} olarak oturum açıldı',
    nearLimit: 'Çalışma alanın eşitlenebilecek boyuta yaklaştı. Bağlantı veya resim simgesi kaldırmak yer açar.',
    'do.sync': 'Şimdi eşitle',
    'do.pause': 'Duraklat',
    'do.resume': 'Sürdür',
    'do.signOut': 'Oturumu kapat',
    'do.signOutHint': 'Eşitlemeyi bu cihazda durdurur. Bu cihazdaki her şey kalır; bulut kopyası kalır.',
    'do.retry': 'Yeniden dene',
    'do.signInAgain': 'Yeniden oturum aç',
    'err.auth-expired': 'Oturumun artık geçerli değil. Sürdürmek için yeniden oturum aç. Bu cihazda hiçbir şey değiştirilmedi.',
    'err.missing': 'Bulut kopyası yok: bulut verileri başka bir cihazda silindi. Bu cihazda hiçbir şey değiştirilmedi ve hiçbir şey yüklenmedi.',
    'err.missingAction': 'Bu cihazın kurulumunu yeniden yükle',
    'err.unreadable': 'Bulut kopyası okunamadı; bu yüzden uygulanmadı. Bu cihazda hiçbir şey değiştirilmedi.',
    'err.went-backwards': 'Bulut kopyası, bu cihazın zaten sahip olduğundan daha eski. Uygulanmadı.',
    'err.too-large': 'Çalışma alanın eşitlenemeyecek kadar büyük. Hiçbir şey gönderilmedi ve kesilmedi. Her şey hâlâ bu cihazda.',
    'err.schema-newer': 'Bulut kopyası daha yeni bir Senuma ile yazılmış. Eşitlemek için bu cihazdaki Senuma’yı güncelle.',
    'err.format-newer': 'Bulut kopyası daha yeni bir Senuma ile yazılmış. Eşitlemek için bu cihazdaki Senuma’yı güncelle.',
    'err.quota': 'Eşitleme hizmeti bugünkü sınırına ulaştı. Daha sonra yeniden denenecek; Senuma çalışmaya devam eder.',
    'err.denied': 'Eşitleme hizmeti isteği reddetti. Yeniden denenecek.',
    'err.failed': 'Eşitleme tamamlanamadı. Yeniden denenecek.',
    'err.offline': 'Eşitleme hizmetine ulaşılamadı.',
    'conflict.title': 'Hem burada hem başka bir cihazda değiştirilen: {n}',
    'conflict.body': 'Bu cihazda da bulutta da hiçbir şey değiştirilmedi. Neyin kalacağını seç. Bir şey uygulanmadan önce geri yükleme noktası kaydedilir.',
    'conflict.local': 'Bu cihaz',
    'conflict.cloud': 'Bulut',
    'conflict.deleted': 'silindi',
    'conflict.order': 'farklı bir sıra',
    'conflict.none': 'yok',
    'conflict.keepLocal': 'Hepsinde bu cihazı tut',
    'conflict.keepCloud': 'Hepsinde bulutu tut',
    'conflict.keepBoth': 'İkisini de tut',
    'conflict.keepBothHint': 'Bu cihazdaki sürüm kalır; buluttaki sürüm yanına ikinci bir bağlantı olarak eklenir.',
    'conflict.keepBothNo': 'İkisini de tutmak yalnızca her fark bir bağlantıdaysa sunulur.',
    'conflict.apply': 'Seçimlerimi uygula',
    'conflict.of.item': '“{name}” bağlantısı',
    'conflict.of.space': '“{name}” Alanı',
    'conflict.of.group': '“{name}” grubu',
    'conflict.of.mode': '“{name}” Modu',
    'conflict.of.provider': 'Arama sağlayıcısı',
    'conflict.of.pref': 'Ayar',
    'conflict.of.dock': 'Dock',
    'conflict.field.exists': 'tutuldu ya da silindi',
    'conflict.field.order': 'sıra',
    'conflict.field.group': 'yer',
    'devices.title': 'Cihazlar',
    'devices.this': 'bu cihaz',
    'devices.last': 'son eşitleme: {when}',
    'devices.unreadable': 'Eski anahtarı kullanan bir cihaz',
    'devices.remove': 'Kaldır',
    'devices.removeHint': 'Bir cihazı kaldırmak onu bu listeden çıkarır; cihaz bir sonraki denemesinde eşitlemeyi bırakır. O cihazda zaten bulunanları silmez ve o cihazdaki Google oturumunu kapatmaz. Kayıp bir cihaz için kurtarma anahtarını da değiştir.',
    'devices.rename': 'Bu cihazın adı',
    'recovery.title': 'Kurtarma anahtarı',
    'recovery.hint': 'Başka bir cihaz eklemek için gerekir.',
    'recovery.show': 'Göster',
    'recovery.confirm': 'Bu anahtarı gören ve Google hesabında oturum açabilen herkes eşitlenen çalışma alanını okuyabilir. Gösterilsin mi?',
    'recovery.yes': 'Anahtarı göster',
    'recovery.hide': 'Gizle',
    'recovery.new': 'Yeni kurtarma anahtarı',
    'recovery.newHint': 'Yeni bir anahtar üretir ve bulut kopyasını yeniden şifreler. Diğer cihazlar, yeni anahtar girilene kadar eşitlemeyi bırakır. Bir cihazın zaten sahip olduklarını geri almaz.',
    'recovery.newConfirm': 'Yeni anahtar üret',
    'delete.title': 'Bulut verilerini sil',
    'delete.hint': 'Şifreli kopyayı, geçmişini, cihaz listesini ve anahtarları hizmetten kaldırır ve burada eşitlemeyi kapatır. Bu cihazdaki her şey kalır.',
    'delete.confirm': 'Bulut verilerini sil',
    cancel: 'Vazgeç',
    'bg.missing': 'Başka bir cihazda seçilen arka plan, bu cihazda olmayan bir resim. Bu cihaz onun yerine temanın arka planını gösteriyor. Diğer cihazlarında hiçbir şey değiştirilmedi.',
    'bg.own': 'Bu cihaz kendi arka planını kullanıyor. Diğer cihazların kendilerininkini koruyor.',
};

export function st(key: SyncKey, params: Record<string, string | number> = {}): string {
    const text: string = (currentLanguage() === 'tr' && tr[key]) || en[key];
    return text.replace(/\{(\w+)\}/g, (match, name: string) => (name in params ? String(params[name]) : match));
}
