import type { HelpStrings } from './strings-en';

/** Help, feedback and review-request strings, Turkish. Loaded only when the interface is Turkish. */
export const HELP_TR: HelpStrings = {
    'section.help': 'Yardım',
    'section.feedback': 'Geri bildirim',
    'help.intro': 'Kullanım kılavuzu Senuma ile birlikte gelir: yeni bir sekmede açılır ve çevrimdışı çalışır.',
    'help.guide': 'Kullanım Kılavuzu',
    'help.guideHint': 'Senuma’nın yaptığı her şey, adım adım.',
    'help.start': 'Başlarken',
    'help.startHint': 'İlk Alanların, görünümün ve bağlantılarını getirmek.',
    'help.keys': 'Klavye Kısayolları',
    'help.keysHint': 'Tüm kısayollar tek bakışta.',
    'help.privacy': 'Gizlilik ve İzinler',
    'help.privacyHint': 'Neyin cihazında kaldığı ve bir iznin neden istendiği.',
    'help.backup': 'İçe Aktarma ve Yedekleme',
    'help.backupHint': 'Yedek dosyaları, geri yükleme noktaları ve bağlantı aktarma.',
    'help.about': 'Senuma Hakkında',
    'help.aboutHint': 'Sürüm ve Senuma’nın ne olduğu.',
    'help.newTab': '(yeni sekmede açılır)',

    'feedback.problem': 'Sorun bildir',
    'feedback.problemHint': 'Doğru çalışmayan şeyler için.',
    'feedback.idea': 'Fikir öner',
    'feedback.ideaHint': 'Özellik ya da iyileştirme önerileri için.',
    'feedback.general': 'Geri bildirim gönder',
    'feedback.generalHint': 'Senuma hakkındaki genel görüşlerin için.',
    'feedback.describe.problem': 'Ne ters gitti?',
    'feedback.describe.idea': 'Senuma’nın ne yapmasını isterdin?',
    'feedback.describe.general': 'Geri bildirimin',
    'feedback.steps': 'Nasıl tekrarlanır (isteğe bağlı)',
    'feedback.tech': 'Teknik bilgileri ekle',
    'feedback.techHint': 'Yalnızca aşağıdaki mesajda görünen satırlar. Alanların, bağlantıların ya da gezintinle ilgili hiçbir şey yok.',
    'feedback.preview': 'E-posta uygulaman bu mesajla açılacak:',
    'feedback.email': 'E-posta uygulamasında aç',
    'feedback.copy': 'Mesajı kopyala',
    'feedback.copied': 'Mesaj kopyalandı',
    'feedback.address': 'Adres: {email}',
    'feedback.private': 'Senuma kendiliğinden hiçbir şey göndermez. E-posta uygulaman bu mesajla açılır; değiştirebilirsin ve gönderip göndermemeye sen karar verirsin.',

    'report.type': 'Tür',
    'report.version': 'Senuma sürümü',
    'report.browser': 'Tarayıcı',
    'report.os': 'İşletim sistemi',
    'report.language': 'Arayüz dili',
    'report.description': 'Açıklama',
    'report.steps': 'Nasıl tekrarlanır',
    'report.tech': 'Teknik bilgiler',
    'report.subject.problem': 'Sorun bildirimi',
    'report.subject.idea': 'Fikir',
    'report.subject.general': 'Geri bildirim',

    'learn.shortcuts': 'Arama kısayolları hakkında daha fazlası',
    'learn.background': 'Doldur, Sığdır, Konum, Bulanıklık ve Atmosfer hakkında',
    'learn.closedTabs': 'Senuma bu izne neden ihtiyaç duyar?',
    'learn.backup': 'Yedekler ve geri yükleme noktaları nasıl çalışır',

    'review.label': 'Değerlendirme isteği',
    'review.title': 'Senuma işine yarıyor mu?',
    'review.body': 'Chrome Web Store’da bırakacağın kısa bir yorum Senuma’nın gelişmesine yardımcı olur.',
    'review.rate': 'Yorum bırak',
    'review.feedback': 'Geri bildirim gönder',
    'review.later': 'Şimdi değil',
};
